# Generated by Django 4.1.7 on 2023-03-30 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('passwd', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
